### ISSUE TITLE
有在colab上部署的示例吗？

### ISSUE THREAD

**Issue by 17837697** [wenda-LLM/wenda#182]
有在colab上部署的示例吗？

**Comment by david5515** [comment]
https://colab.research.google.com/drive/1H97tm1dWi7qW1qg371HPKf269Clsvn5-?usp=sharing
我当时是4月12号左右的版本，能跑起来，后面我就在本地跑了，你可以参照试试

**Comment by 17837697** [comment]
试了一下，现在已经变了很多了，已经无法跑通了

**Comment by chenhao9255** [comment]
> 试了一下，现在已经变了很多了，已经无法跑通了

希望大牛能同步在colab上，配环境和网速都比本地好很多~~~
