### ISSUE TITLE
纯git下载后readme启动流程走不通，不想下载懒人包

### ISSUE THREAD

**Issue by millionart** [wenda-LLM/wenda#230]
说明页面是基于下载了懒人包的运行步骤，如果我不想下载懒人包，上手步骤就完全看不懂

- 比如怎么配置config.xml，模型放在哪，对应的路径应该填什么，没有示例
- 各个 requirements.txt 对应的用途和模型也找不到
- fess 除了从懒人包提取还有什么其他方法？
- 不用 fess 怎么启动

知乎页面也是多个最新更新反复堆砌，分不清哪个是最新，下面的内容也是逻辑混乱过于技术性了

希望文档能仔细完善一下，作为语言模型，文档信息传递水平起码要在模型以上，否则真的劝退

**Comment by millionart** [comment]
![image](https://user-images.githubusercontent.com/7535532/236223001-1c60a93c-0f4c-4aa3-ac53-7f2318fbef92.png)
按照这个文档：

- 怎么配置 config.xml，模型放在哪，对应的路径应该填什么
- 如何启动项目，完全没有写

**Comment by l15y** [comment]
exmaple.config.xml看一下
