### ISSUE TITLE
【FR】通过Auto脚本实现流式总结pdf文件的要点

### ISSUE THREAD

**Issue by wwjCMP** [wenda-LLM/wenda#232]
通过auto脚本有没有可能实现以下功能，提供一个pdf文件，处理为向量数据缓存后。让闻达不断低读取指定长度的信息，然后提炼总结要点，流式地处理完pdf中的所有信息。同时将信息写到指定文件中，处理完后删除pdf的缓存。

**Comment by l15y** [comment]
可以，但是要自己实现读取pdf。https://github.com/AlanLee1996/wenda-webui 这个项目的作者在做

**Comment by AlanLee1996** [comment]
已经做了文档对话了，分片总结下周更新。

**Comment by l15y** [comment]
已经有了
