### ISSUE TITLE
知识库启动后无法回答复杂问题

### ISSUE THREAD

**Issue by flizzywine** [wenda-LLM/wenda#290]
选择开启知识库后，如果问一些简短的词语，能够正常回答。
但是如果问稍微复杂一些些的问题，就无法回答。
如下图：
开启知识库，询问简短的词语：
![image](https://github.com/wenda-LLM/wenda/assets/27564130/ceb9f381-3e79-4c12-b813-2c7c777745d6)

开启知识库，询问稍微复杂的短语：
![image](https://github.com/wenda-LLM/wenda/assets/27564130/bf7457ab-3552-4950-b7e6-4b4ca1d11e39)

配置：

library: 
     strategy: "bing:5"

llm_type: rwkv
#llm模型类型:glm6b、rwkv、llama、replitcode等，详见相关文件
llm_models: 
  rwkv: 
     path: "model/RWKV-4-Raven-7B-v9x-Eng49%-Chn50%-Other1%-20230418-ctx4096.pth"      #rwkv模型位置"
     strategy: "cuda fp16i8 *10+"

**Comment by dytxy888** [comment]
我找到了一个临时解决办法，bing搜索有一个特性，直接爬会返回空结果，如果你人工用浏览器搜索过某个关键词，再爬bing就会从本地缓存中返回结果。根据这一特点，可以在python爬取脚本中，先调用os打开传参的浏览器，显示结果后关闭浏览器，接着再常规爬就行。
经测试成功，偶尔首次会返回空，后续很稳定。
