### ISSUE TITLE
在Ubuntu上启动失败

### ISSUE THREAD

**Issue by 1945083536** [wenda-LLM/wenda#294]
**Describe the bug**
在ubuntu上启动失败，报错如下
![image](https://github.com/wenda-LLM/wenda/assets/13993532/e0c88dcf-6653-4d81-adcf-b0237b1a7a2b)

**To Reproduce**
1. 从网盘上下载程序和模型
2. 调整config，设置为fp16i4
3. 运行 python wenda.py -t glm6b

**Expected behavior**
正常启动

**Screenshots**
![image](https://github.com/wenda-LLM/wenda/assets/13993532/92ddd838-ed6f-4e79-ad36-9bc3f63e7593)

**Desktop (please complete the following information):**
 - Ubuntu

**Additional context**

**Comment by l15y** [comment]
看起来模型没下好
