### ISSUE TITLE
请问知识库的txt文件是否需要按照某种格式格式来写？

### ISSUE THREAD

**Issue by lmdegit** [wenda-LLM/wenda#300]
我目前的txt内容格式如下：

问：商业贷款还贷提取条件？本地购房商贷还贷提取条件？异地商贷还贷提取要求？
答：商贷（本地、异地）还贷提取条件：
1.职工须在正常还款2个月后提出申请，每年可提取一次，两次提取时间间隔不少于12个月。
2.发生提前部分还款的，可在还款后的12个月内申请提取一次；且不受两次提取时间间隔12个月的限制。
3.发生（提前）结清的，可在结清后的12个月内申请提取一次，且不受两次提取时间间隔12个月的限制。

意思是3个问题对应一个答案，不知道这样是否可行？

**Comment by l15y** [comment]
可以看看rtst客服这个auto，专门用于你这个情况
