### ISSUE TITLE
配置llm模型strategy使用GPU，GPU正常使用，但CPU只用了单核

### ISSUE THREAD

**Issue by HUIHUIABC** [wenda-LLM/wenda#303]
linux上，配置llm模型strategy使用gpu，监测到gpu正常运算，但是监测cpu只是用了单核并且跑满，以至于cpu成为了算力瓶颈。如下图，gpu正常使用，但96个cpu只用了1个。

![2023-05-19 (3)](https://github.com/wenda-LLM/wenda/assets/27758750/d4a01e19-01c3-45d7-a6be-3ab8f06e3a27)

![2023-05-19 (2)](https://github.com/wenda-LLM/wenda/assets/27758750/717ff6dc-9d55-42d1-bcf8-6a35fc215d8f)

运行环境：Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-125-generic x86_64)

请问大佬们怎么样可以用到多cpu提速？

**Comment by l15y** [comment]
你的cup太弱，不计划做多进程
