### ISSUE TITLE
建议后续集成Claude 100K的模型

### ISSUE THREAD

**Issue by lsmegranate** [wenda-LLM/wenda#310]
Claude 已将语境窗口 token 数扩展到 10 万，相当于 7.5 万个单词，大大超越了 GPT-4 语境窗口的 8192 tokens。这意味着用户可以将高达 500 页的文档上传到 Claude，它可以在不到 1 分钟之内就理解、消化这些信息，并基于上传的信息回答用户的问题。

tokens对于知识库来讲是个很关键的因素，建议考虑集成这个api。

https://www.sohu.com/a/675785538_114760

**Comment by l15y** [comment]
有开放api了？

**Comment by lsmegranate** [comment]
> 有开放api了？

可以申请API了，但是貌似API要付费
