### ISSUE TITLE
服务能正常启动 接口地址不能调用  http://127.0.0.1:17860/api/find

### ISSUE THREAD

**Issue by wdkrdem** [wenda-LLM/wenda#311]
服务能正常启动 接口地址不能调用  http://127.0.0.1:17860/api/find
请看图示
![001](https://github.com/wenda-LLM/wenda/assets/21660751/b1a45102-4271-4ffc-8a2b-e0cd5c876290)
![002](https://github.com/wenda-LLM/wenda/assets/21660751/1110c9f9-7896-49d6-a911-5337e0009c7d)

**Comment by l15y** [comment]
显然是因为你将端口改成了7099
