### ISSUE TITLE
请问如何配置多显卡

### ISSUE THREAD

**Issue by wdkrdem** [wenda-LLM/wenda#312]
请问如何配置多显卡

**Comment by Sowhat007** [comment]
config里面改改参数，比如如果是glm6b，就在strategy里写上cuda fp 16。或者试试作者推荐的方式：
`llm_models: 
  rwkv: 
     path: "model/rwkv-4-raven-7b-v11.pth"      #rwkv模型位置"
     strategy: "cuda fp16i8"
   #   path: "model/rwkv_ggml_q8.bin"           #rwkv模型位置"
   #   strategy: "Q8_0"       #rwkvcpp:运行方式，设置strategy诸如"Q8_0->16"即可开启，代表运行Q8_0模型在16个cpu核心上
     #rwkv模型参数"
    
     historymode: state
     #rwkv历史记录实现方式：state、string
  glm6b: 
     path: "model/chatglm-6b"
     #glm模型位置"
     strategy: "cuda fp16"
     #cuda fp16	 所有glm模型 要直接跑在gpu上都可以使用这个参数
     #cuda fp16i8	 fp16原生模型 要自行量化为int8跑在gpu上可以使用这个参数
     #cuda fp16i4	 fp16原生模型 要自行量化为int4跑在gpu上可以使用这个参数
     #cuda:0 fp16 *14 -> cuda:1	fp16 多卡流水线并行，使用方法参考RWKV的strategy介绍。总层数28`

**Comment by biaggii** [comment]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)
