### ISSUE TITLE
希望作者能集成VisualGLM-6B

### ISSUE THREAD

**Issue by ng-fukgin** [wenda-LLM/wenda#313]
清华开源了[VisualGLM-6B](https://github.com/THUDM/VisualGLM-6B)，我在本地部署成功了，相关的demo也跑通了，我想讲这个功能集成进来，但是我不太懂html，js之类的，不知道怎么在wenda界面上传图片以及发送图片到api里面，你能把这个功能集成进来吗？或者你简单告诉我应该怎么做，我去尝试下.

**Comment by l15y** [comment]
可以尝试修改群友做的clip支持。最近暂时没时间做

**Comment by l15y** [comment]
群友实现了，在群共享
