### ISSUE TITLE
请问如何在bingsite里添加多个网页支持

### ISSUE THREAD

**Issue by zdoek001** [wenda-LLM/wenda#317]

**Comment by arksaga** [comment]
登录到 bingsite 并选择你要添加网页的网站
点击左侧导航栏的 “网页” 选项。点击右上角的 “添加网页” 按钮。输入你要添加的网页的标题、描述、关键词和 URL点击 “保存” 按钮。你可以重复这些步骤来添加更多的网页支持。你也可以通过 “编辑” 或 “删除” 按钮。
