### ISSUE TITLE
chatglm跑不起来，sentence-transformer问题，llama.cpp跑起来更慢了

### ISSUE THREAD

**Issue by Sowhat007** [wenda-LLM/wenda#319]
1，下载了chatglm-6b模型（包含8个bin文件），在config中指定了地址，运行的时候会加载不了模型。可以看到两个提示信息：
1.1没有读取到LLM参数，可能是因为当前模型为API调用。
1.2File "wenda.py", line 44, in load_model
    LLM.load_model()
AttributeError: 'NoneType' object has no attribute 'load_model'

2，按提示下载了[GanymedeNil/text2vec-large-chinese](https://huggingface.co/GanymedeNil/text2vec-large-chinese)，会提示报警：
No sentence-transformers model found with name /data/liaoji/text2vec-large-chinese. Creating a new one with MEAN pooling.
查了下sentencetransformer源码，是因为GanymedeNil/text2vec-large-chinese下载下来没有modules.json文件，所以识别不了，不知道做这是否是自行补充了相关文件。

3，试了一下量化llama模型，可以运行，但是速度非常慢，不调用知识库的情况下速度会比非量化版本慢，调用知识库会更慢（可能和第二个问题有关）。

**Comment by l15y** [comment]
1你上面还有报错，去看
2没事

**Comment by Sowhat007** [comment]
感谢回复！
看了下，第一个问题，中间还报了一个错说
LLM模型加载失败，请阅读说明：https://github.com/l15y/wenda No module named 'wudao'。我试着看看是不是包没装上。

2，确实没事，在其他帖子也看到了类似问题。开始我以为完全换了个预设的模型，效果打折扣了，其实不会。缺少的文件不建议自己补充。

**Comment by Sowhat007** [comment]
手动安装了wudao包，报了另一个错：
LLM模型加载失败，请阅读说明：https://github.com/l15y/wenda 'GLM_API_KEY'
估计是此处认为在调用api，所以需要填api_key。再看看是哪里出了问题。

**Comment by Sowhat007** [comment]
检查后发现错误是因为我本地是chatglm-6b模型而我用了python wenda.py -t chatglm这个命令，这个命令本身有问题，换为python wenda.py -t glm6b就可以了。

效果很棒，实测推理速度会比imClumsyPanda大大的langchain-ChatGLM项目更快（都不加知识库或者都加上知识库的情况下均如此）。但其实模型加载是一样的，还需要再研究下什么原因导致的。

**Comment by l15y** [comment]
那个命令是api
