### ISSUE TITLE
Ubuntu执行gen_data_st.py构建索引最后一步出错

### ISSUE THREAD

**Issue by ghtHack** [wenda-LLM/wenda#323]
执行 python plugins/gen_data_st.py后，出错

...省略输出若干

处理完成
合并至已有索引。如不需合并请删除 memory/default 文件夹
新建索引
╭───────────────────────────── Traceback (most recent call last) ─────────────────────────────╮
│ /home/ght/桌面/wenda/plugins/gen_data_st.py:140 in <module>                              │
│                                                                                             │
│   137 │   vectorstore_old = FAISS.load_local(                                               │
│   138 │   │   'memory/default', embeddings=embeddings)                                      │
│   139 │   success_print("合并至已有索引。如不需合并请删除 memory/default 文件夹")           │
│ ❱ 140 │   vectorstore_old.merge_from(vectorstore)                                           │
│   141 │   vectorstore_old.save_local('memory/default')                                      │
│   142 except:                                                                               │
│   143 │   print("新建索引")                                                                 │
│                                                                                             │
│ /home/ght/.conda/envs/wanshitong/lib/python3.10/site-packages/langchain/vectorstores/faiss. │
│ py:322 in merge_from                                                                        │
│                                                                                             │
│   319 │   │   starting_len = len(self.index_to_docstore_id)                                 │
│   320 │   │                                                                                 │
│   321 │   │   # Merge two IndexFlatL2                                                       │
│ ❱ 322 │   │   self.index.merge_from(target.index)                                           │
│   323 │   │                                                                                 │
│   324 │   │   # Create new id for docs from target FAISS object                             │
│   325 │   │   full_info = []                                                                │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'index'

During handling of the above exception, another exception occurred:

╭───────────────────────────── Traceback (most recent call last) ─────────────────────────────╮
│ /home/ght/桌面/wenda/plugins/gen_data_st.py:144 in <module>                              │
│                                                                                             │
│   141 │   vectorstore_old.save_local('memory/default')                                      │
│   142 except:                                                                               │
│   143 │   print("新建索引")                                                                 │
│ ❱ 144 │   vectorstore.save_local('memory/default')                                          │
│   145 success_print("保存完成")                                                             │
│   146                                                                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'save_local'

**Comment by philipyao** [comment]
raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by ghtHack** [comment]
> ```
> raise AssertionError("Torch not compiled with CUDA enabled")
> ```
> 
> 有这个错么？如果有， pytorch 库要安装带 cuda 版本的。（另外吐槽一下，这个项目的说明写的稀烂，各种环境问题报错）

感谢提醒，虽然不是这个错误，但是给了我解决问题的思路，修改代码model_path, device="cpu") #cuda 后解决问题
