### ISSUE TITLE
ChatPLUG

### ISSUE THREAD

**Issue by imshadow** [wenda-LLM/wenda#325]
能否支持[ChatPLUG ](https://modelscope.cn/models/damo/ChatPLUG-3.7B/summary)，这个是阿里开源的小模型，感觉也挺不错

**Comment by diannaojiang** [comment]
推理程序的连接https://github.com/X-PLUG/ChatPLUG/blob/main/XDPX/scripts/fidchat_new.py   我去看了下源码实现，阿里为了推广他的modelscope，使用xdpx来对整个推理程序进行了封装。要做结构分析、pytorch复现，需要一定的人力时间。所以如果有很多人支持添加，才会提上适配日程。

**Comment by imshadow** [comment]
> 推理程序的连接https://github.com/X-PLUG/ChatPLUG/blob/main/XDPX/scripts/fidchat_new.py https://github.com/X-PLUG/ChatPLUG/blob/main/XDPX/xdpx/utils/chat/pipeline.py 我去看了下源码实现，阿里为了推广他的modelscope，使用xdpx来对整个推理程序进行了封装。要做结构分析、pytorch复现，需要一定的人力时间。所以如果有很多人支持添加，才会提上适配日程。

好的
