### ISSUE TITLE
求教部署在服务器后怎么在公网提供服务？

### ISSUE THREAD

**Issue by Sowhat007** [wenda-LLM/wenda#326]
作者你好，感谢你做了这么好的应用！RT，怎么做到在公网可以访问网页。我看到这里是用的bottle，问了一下gpt怎么改bottle参数但是没得到很好的回复。之前用gradio的项目是直接share=True完成的，这里是不是也是类似的操作？

**Comment by l15y** [comment]
直接通过服务器ip访问

**Comment by Sowhat007** [comment]
成功了！感谢大大
