### ISSUE TITLE
现阶段通过wenda远程访问局域网其他电脑sd是否可行

### ISSUE THREAD

**Issue by zhuyunqi1990** [wenda-LLM/wenda#328]
你好，作者
背景：内网中的其他电脑已经部署并开放了sd的api端口，通过python代码已经能够从其他电脑调用这个api并将图片保存到本地了。
问题：这次新增加的wenda 绘图功能，查看auto里的脚本代码，不知如何才能修改才能让agent识别某个特定内网地址。目前在该脚本中尝试修改网址，也无法事先画图的功能，返回的都是“并将SD API地址设置为127.0.0.1:786”这条信息
总结：非本地sd怎么才能让wenda识别

**Comment by l15y** [comment]
一样的
