### ISSUE TITLE
报错：clang: error: unsupported option '-fopenmp'，请大神指导，谢谢啦

### ISSUE THREAD

**Issue by lwo2002** [wenda-LLM/wenda#329]
mac m1 pro，osx=ventura 13.4 
已经安装了支持mps的pytorch，安装了omp，不过还是出现：clang: error: unsupported option '-fopenmp'的错误，请各位大神指导，谢谢

**Comment by arksaga** [comment]
你可能遇到了一个常见的问题，就是在 Mac M1 上使用 clang 编译器时无法支持 -fopenmp 选项，这个选项是用来启用 OpenMP 并行编程的。有一些可能的解决方案，你可以尝试以下的方法：
