### ISSUE TITLE
LLM模型加载失败，librwkv.dylib' (no such file)

### ISSUE THREAD

**Issue by BboyIcee** [wenda-LLM/wenda#331]
环境：mac python3.8

已下载RWKV模型到model文件夹
![image](https://github.com/wenda-LLM/wenda/assets/132138881/1d4757dc-3004-4037-b92c-23f0eeefb9af)

同时进行了config配置
![image](https://github.com/wenda-LLM/wenda/assets/132138881/24f97e6a-788d-4375-a383-32827b023e79)

执行sh run_rwkv.sh时报错
OSError: dlopen(/Users/bytedance/Downloads/wenda/llms/rwkvcpp/librwkv.dylib, 0x0006): tried: '/Users/bytedance/Downloads/wenda/llms/rwkvcpp/librwkv.dylib' (no such file), '/usr/local/lib/librwkv.dylib' (no such file), '/usr/lib/librwkv.dylib' (no such file)

请问是哪里出错，怎么修复？

**Comment by l15y** [comment]
说明里写了，要下那个2进制文件

**Comment by BboyIcee** [comment]
> 

哪个说明里写的啊，下哪个2进制文件？

**Comment by l15y** [comment]
https://github.com/wenda-LLM/wenda#cpp
