### ISSUE TITLE
使用RWKV模型，生成结果在胡说八道

### ISSUE THREAD

**Issue by BboyIcee** [wenda-LLM/wenda#332]
![image](https://github.com/wenda-LLM/wenda/assets/132138881/af10e401-fadf-4cb2-98f3-7dcff6c7ac7a)
![image](https://github.com/wenda-LLM/wenda/assets/132138881/7c89dff3-3ef4-4064-8dda-5f46fbebd240)
![image](https://github.com/wenda-LLM/wenda/assets/132138881/374b3ad2-0076-4c60-9e7e-82dacf618aa8)

请问是哪里出错？没办法正常生成小说

**Comment by l15y** [comment]
模型本身问题去对应项目问
