### ISSUE TITLE
run_llama.sh failed to load model

### ISSUE THREAD

**Issue by alexhmyang** [wenda-LLM/wenda#338]
llama.cpp: loading model from /home/u20/wenda/llama.cpp/models/7B/4bit/model/ggml-model-q4_0.bin
error loading model: unknown (magic, version) combination: 67676a74, 00000003; is this really a GGML file?
llama_init_from_file: failed to load model
Exception in thread Thread-1:

-----
可能是模型不匹配？

发现同样的问题：https://github.com/ParisNeo/gpt4all-ui/issues/129

-----

同时，英文的分词找相似应该用哪个模型，config.yml里没有写，我们找了一个  

paraphrase-multilingual-MiniLM-L12-v2模型名称是[sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2](https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2)，是用SBERT训练，是paraphrase-MiniLM-L12-v2模型的多语言版本，支持中文、英文等

**Comment by alexhmyang** [comment]
换了llama 之后成功运行了，但是 很慢，一直没出结果


llama.cpp: loading model from /home/u20/Downloads/ggml-vicuna-7b-1.1-q4_2.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 4096
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 5 (mostly Q4_2)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =  68.20 KB
llama_model_load_internal: mem required  = 5809.33 MB (+ 1026.00 MB per state)
warning: failed to mlock 73728-byte buffer (after previously locking 0 bytes): Cannot allocate memory
Try increasing RLIMIT_MLOCK ('ulimit -l' as root).
warning: failed to mlock 81920000-byte buffer (after previously locking 0 bytes): Cannot allocate memory
Try increasing RLIMIT_MLOCK ('ulimit -l' as root).
....................................................................................................
llama_init_from_file: kv self size  = 2048.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
模型加载完成
serving on 0.0.0.0:17860 view at http://127.0.0.1:17860
知识库加载完成


Llama.generate: prefix-match hit

运行到这里一直在运行 ，一直没出结果

**Comment by alexhmyang** [comment]
等了大概3分钟才出结果

**Comment by taburise** [comment]
这是CPU在跑模型，慢是正常的

**Comment by l15y** [comment]
要改成torch模式和相应模型

**Comment by alexhmyang** [comment]
> 要改成torch模式和相应模型

![image](https://github.com/wenda-LLM/wenda/assets/10215059/f08130bc-9157-459b-ad3a-fd9ef32591e8)
     strategy: "cuda fp16i4"
     加了 cuda了，没用呀

**Comment by l15y** [comment]
你应该先了解一下llama torch的官方调用方法，是一样的

**Comment by alexhmyang** [comment]
> 你应该先了解一下llama torch的官方调用方法，是一样的

我上面已经 按照 example config 下载了 q4_2.bin, 但是 运行起来非常慢 ，我本身加载的 llms 就是 量化后的模型 还有啥问题？

我原来也单独运行过lamma lora, 没有遇到现在的问题

另外，这个llama模型 用的是哪个知识库搜索模型 rtst ？ 没看到你有为 llama 单独配置 像 中文6b 一样的  text2vec-large-chinese 。 我自己找了一个 英文的text2vec模型，可以用吗？ 还是 llama本身不需要 文本匹配？

**Comment by l15y** [comment]
q4格式是cpu推理，建议用torch
LLM与rtst是解耦的

**Comment by alexhmyang** [comment]
> q4格式是cpu推理，建议用torch LLM与rtst是解耦的

您的意思是 wenda不支持llama 配置吗？ 得我自己重新找别的方案？还是 wenda支持（要怎么配置呢）？
