### ISSUE TITLE
运行CUDA_VISIBLE_DEVICES=1,2 bash run_rwkv.sh，报错显存不够

### ISSUE THREAD

**Issue by dizhenx** [wenda-LLM/wenda#348]
执行命令CUDA_VISIBLE_DEVICES=1,2 bash run_rwkv.sh
报错cuda out of memory。看了以下显存占用情况，虽然允许两块gpu执行，但是实际加载只用了第一个gpu，而且此命令会开启3个进程占用，加起来的显存占用超过单卡11G的显存量，导致报错。
3个进程分别是啥？其中一个应该是加载语言模型，另外两个是啥？另外两个进程能否不用gpu加载?
为啥chatglm占用显存小可以跑，而rwkv占用多？还有为啥只能单卡运行，不能多卡吗? 是int8量化加载的，能否改为int4加载模型？

**Comment by l15y** [comment]
去rwkv项目，学参数设置
