### ISSUE TITLE
ubuntu 源码运行openai模型 如何启动 bing模式？

### ISSUE THREAD

**Issue by alexhmyang** [wenda-LLM/wenda#355]
ubuntu 源码运行openai模型 如何启动 bing模式？
谢谢

**Comment by l15y** [comment]
知识库参数增加 bing:3

**Comment by alexhmyang** [comment]
> 知识库参数增加 bing:3

加了，运行起来了，但是 对话起来 好像 有时有搜索，有时又没有搜索，来源出处有时有，有时没有，咋回事？

**Comment by l15y** [comment]
bing本身有反爬虫
