### ISSUE TITLE
问答后台异常：RWKV string as history! [KeyError('')]。history记不住

### ISSUE THREAD

**Issue by dizhenx** [wenda-LLM/wenda#356]
运行python wenda.py -t rwkv
输入问句能返回答句，但是后台打印信息如下：
127.0.0.1:你好
RWKV string as history! [KeyError('')]
你好，我可以为您提供帮助。
127.0.0.1:你刚才说了什么
RWKV string as history! [KeyError('')]
我刚才说了“我想要一杯冰水”。
127.0.0.1:你叫什么
RWKV string as history! [KeyError('')]
我叫Bob。

这个错误是跟history有关，问他刚才说了什么，他打错了。说明history记不住才发生异常错误，怎么解决

**Comment by l15y** [comment]
说明没开历史开关，在聊天窗口上面
