### ISSUE TITLE
对话框中，提问和修改后的prompt能否不显示出来？

### ISSUE THREAD

**Issue by hopeforus** [wenda-LLM/wenda#359]
如题，我们在对话框中输入问题后，点击“发送”，对话框中问题和系统匹配的prompt都会显示出来，能否把对话框中显示的这个过程关掉？

**Comment by l15y** [comment]
可以

**Comment by hopeforus** [comment]
在哪里设置或修改呢？

**Comment by l15y** [comment]
过两天做

**Comment by hopeforus** [comment]
谢谢！

**Comment by l15y** [comment]
已更新

**Comment by hopeforus** [comment]
厉害👍
| |
胡红亮
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月06日 17:40 |
| 收件人 | wenda-LLM/wenda ***@***.***> |
| 抄送人 | hopeforus ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [wenda-LLM/wenda] 对话框中，提问和修改后的prompt能否不显示出来？ (Issue #359) |

已更新

**Comment by hopeforus** [comment]
多谢！高效！
