### ISSUE TITLE
懒人包安装完后运行未找到“语义知识库计算模型”

### ISSUE THREAD

**Issue by DeepBlueZh** [wenda-LLM/wenda#362]
你好，我是6.2日版本，懒人包正常按照教程安装，安装完后复制到C盘运行，启动的时候遇到两个问题：
1. 加载配置失败。
2. 没有找到model文件夹里的text2vec-large-chinese（我确实解压了这个东西把他们放在model里）
报错截图如下：
![image](https://github.com/wenda-LLM/wenda/assets/131225582/1d38b79f-4def-4881-817b-8699028a6bb6)
![image](https://github.com/wenda-LLM/wenda/assets/131225582/836dd424-99d1-4a21-a640-2b43911e48aa)
我的文件夹如下：
![image](https://github.com/wenda-LLM/wenda/assets/131225582/0e66d5e1-3323-430c-a6e6-da19b0e3562b)

**Comment by DeepBlueZh** [comment]
请大佬帮我看下这个问题，我是个计算机小白，万分感谢。

**Comment by DeepBlueZh** [comment]
你好我已经解决了未找到语义知识库计算模型的问题，原因是我的压缩软件会自动生成一个一样名字的文件夹，导致路径识别有问题，我改了路径就好了。
我在构建知识库的时候发现目前还不支持XLSX和JPG文件，请问这个后续有计划吗？因为要处理很多表格。

**Comment by DeepBlueZh** [comment]
似乎目前也不支持DOCX....

**Comment by l15y** [comment]
是的
