### ISSUE TITLE
API接口报500错误

### ISSUE THREAD

**Issue by SunkenStar** [wenda-LLM/wenda#364]
**Describe the bug**
 配合chatGPTBox使用时无法正常工作

**To Reproduce**
[见chatGPTBox的这条issue](https://github.com/josStorer/chatGPTBox/issues/397)，目前很可能只有我遇见了这个问题

**Expected behavior**
chatGPTBox可以正常工作

**Screenshots**
在把`wenda.py`的uvicorn的log_level之后每次让chatGPTBox访问接口都可以看到输出`INFO:     127.0.0.1:38754 - "OPTIONS /completions HTTP/1.1" 500 Internal Server Error`
**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser: Firefox
**Additional context**
可能是arch的问题，不过自带的ui和wenda-webui都工作正常，所以大概率不是

**Comment by l15y** [comment]
不用改接口地址
