### ISSUE TITLE
请问文档中提到的多用户同时使用是如何实现的

### ISSUE THREAD

**Issue by rDearApple** [wenda-LLM/wenda#365]
请问文档中提到的多用户同时使用是如何实现的

**Comment by ImmNaruto** [comment]
排队机制，访问前先调chat_now接口获取排队人数

**Comment by l15y** [comment]
> 排队机制，访问前先调chat_now接口获取排队人数

正解

**Comment by l15y** [comment]
> 排队机制，访问前先调chat_now接口获取排队人数

正解

**Comment by samzhang82** [comment]
谢谢

**Comment by rDearApple** [comment]
> 排队机制，访问前先调chat_now接口获取排队人数

感谢

**Comment by tq0426w** [comment]
如果同时有10个用户访问websocket接口，chatglm-6b模型可以同时对这10个问题生成答案，然后使用websocket接口同时返回给这10个用户吗？还是说同一时间只有一个用户可以接收答案，其他9个用户只能干等着呢？

**Comment by l15y** [comment]
> 如果同时有10个用户访问websocket接口，chatglm-6b模型可以同时对这10个问题生成答案，然后使用websocket接口同时返回给这10个用户吗？还是说同一时间只有一个用户可以接收答案，其他9个用户只能干等着呢？

后者，原因请学习一下llm的推理过程
