### ISSUE TITLE
用了多個放法都不行  Expected all tensors to be on the same device, but found at least two devices

### ISSUE THREAD

**Issue by biaggii** [wenda-LLM/wenda#370]
用了多個放法都不行, 只有在單個卡上才可以, 其他都rumtime error
path: 'Y:/Ai/LLM/GPT/Models/RWKV-4-Raven-7B-v12-Eng49%-Chn49%-Jpn1%-Other1%-20230530-ctx8192.pth'
strategy: 'cuda fp16'
# path: 'Y:/Ai/LLM/GPT/Models/RWKV-4-Raven-14B-v12-Eng98%-Other2%-20230523-ctx8192.pth'
# strategy: 'cuda:1 fp16 *0+ -> cpu fp32 *1'
# strategy: 'cuda:0 fp16 *0+ -> cuda:1 fp16 *10'
# strategy: 'cuda:1 fp16 *20 -> cuda:0 fp16'
# strategy: 'cuda:0 fp16 *14 -> cuda:1 fp16'

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat)

**Comment by l15y** [comment]
rwkv的多state转存目前只支持但卡，下个版本做个自动开关

**Comment by l15y** [comment]
前几天修了，试试
