### ISSUE TITLE
并发量大时页面响应慢，是否可以增加排队流量控制机制

### ISSUE THREAD

**Issue by opsvr202** [wenda-LLM/wenda#374]
当并发量大时，能明显感觉页面卡顿，显卡CPU使用飙升，问题响应慢。
十分可以增加排队机制，控制并发量，问题根据先后排队响应。

**Comment by ImmNaruto** [comment]
排队机制现在是有的，控制并发量的话你可以在调用接口前先获取等待人数（waiting_threads），超过一个阈值就不加入队列里直接挡掉
