### ISSUE TITLE
rwkv world mode! No sentence-transformers model found with name model/m3e-base. Creating a new one with MEAN pooling.

### ISSUE THREAD

**Issue by holalahy** [wenda-LLM/wenda#378]
懒人包，运行服务RWKV，报如下错误，不知是我哪里弄错了吗？谢谢！
![image](https://github.com/wenda-LLM/wenda/assets/67778331/596cb27e-2562-4525-9bb4-e22f7acc2bf7)

**Comment by l15y** [comment]
> No sentence-transformers model found with name model/m3e-base. Creating a new one with MEAN pooling.
是知识库模型报的，没事
