### ISSUE TITLE
"加载配置失败，改为加载默认配置"

### ISSUE THREAD

**Issue by shadowbox-cash** [wenda-LLM/wenda#386]
**Describe the bug**
运行 python3 plugins/gen_data_st.py 报错“加载配置失败，改为加载默认配置”，
我已经把example.config.yml改成config.yml 

**To Reproduce**
运行 python3 plugins/gen_data_st.py 报错“加载配置失败，改为加载默认配置”，
我已经把example.config.yml改成config.yml 
得到报错如下：

加载配置失败，改为加载默认配置
library:
  count: 5
  step: 2
  strategy: calc:2 rtst:2 agents:0
librarys:
  bing:
    count: 5
  bingsite:
    count: 5
    site: www.12371.cn
  fess:
    count: 1
    fess_host: 127.0.0.1:8080
  kg:
    count: 5
    graph_host: ''
    knowledge_path: ''
    model_path: ''
  qdrant:
    collection: qa_collection
    device: cpu
    model_path: model/text2vec-large-chinese
    path: txt
    qdrant_host: http://localhost:6333
  remote:
    host: http://127.0.0.1:17860/api/find
  rtst:
    count: 3
    device: cuda
    model_path: model/m3e-base
    overlap: 0
    size: 20
llm:
  historymode: state
  path: model/RWKV-4-World-7B-v1-OnlyForTest_52%_trained-20230606-ctx4096-i8.pth
  state_source_device: cpu
  strategy: cuda fp16i8
llm_type: rwkv
logging: false
port: 17860

Embedding 加载完成
文件列表生成完成 1
处理进度 100 %
处理完成
合并至已有索引。如不需合并请删除 memory/default 文件夹
保存完成

因为没有根据我配置的使用chatGLM模型，默认使用 在执行 wenda.py 报如下错误：
加载配置失败，改为加载默认配置
library:
  count: 5
  step: 2
  strategy: calc:2 rtst:2 agents:0
librarys:
  bing:
    count: 5
  bingsite:
    count: 5
    site: www.12371.cn
  fess:
    count: 1
    fess_host: 127.0.0.1:8080
  kg:
    count: 5
    graph_host: ''
    knowledge_path: ''
    model_path: ''
  qdrant:
    collection: qa_collection
    device: cpu
    model_path: model/text2vec-large-chinese
    path: txt
    qdrant_host: http://localhost:6333
  remote:
    host: http://127.0.0.1:17860/api/find
  rtst:
    count: 3
    device: cuda
    model_path: model/m3e-base
    overlap: 0
    size: 20
llm:
  historymode: state
  path: model/RWKV-4-World-7B-v1-OnlyForTest_52%_trained-20230606-ctx4096-i8.pth
  state_source_device: cpu
  strategy: cuda fp16i8
llm_type: rwkv
logging: false
port: 17860

rwkv world mode!
RWKV_JIT_ON 1 RWKV_CUDA_ON 0 RESCALE_LAYER 6

Loading model/RWKV-4-World-7B-v1-OnlyForTest_52%_trained-20230606-ctx4096-i8.pth ...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/miniconda3/envs/myenv/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/myenv/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/root/wenda/wenda.py", line 50, in load_model
    LLM.load_model()
  File "/root/wenda/llms/llm_rwkv.py", line 312, in load_model
    model = RWKV(model=settings.llm.path, strategy=settings.llm.strategy)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/jit/_script.py", line 292, in init_then_script
    original_init(self, *args, **kwargs)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/rwkv/model.py", line 104, in __init__
    self.w = torch.load(args.MODEL_NAME, map_location='cpu') # load model to CPU first
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'model/RWKV-4-World-7B-v1-OnlyForTest_52%_trained-20230606-ctx4096-i8.pth'
No sentence-transformers model found with name model/m3e-base. Creating a new one with MEAN pooling.
知识库加载完成

---------------------------------------

以下是我的config.yml，是哪里不对吗？ 我只修改了llm type为llm_type: glm6b；
同时修改了我的chatGLM地址为“path: "/chatGLM/chatglm-6b-int4”，地址是真实存在的；

logging: False
#日志"
port: 17860
#webui 默认启动端口号"
library: 
     strategy: "calc:2 rtst:2 agents:0"
     #库参数，每组参数间用空格分隔，冒号前为知识库类型，后为抽取数量。

     #知识库类型:
     #bing        cn.bing搜索，仅国内可用，目前处于服务降级状态
     #sogowx      sogo微信公众号搜索，可配合相应auto实现全文内容分析
     #fess        fess搜索引擎
     #rtst        支持实时生成的sentence_transformers
     #remote      调用远程闻达知识库，用于集群化部署
     #kg          知识图谱,暂未启用
     #特殊库：
     #mix         根据参数进行多知识库融合
     #agents      提供网络资源代理，没有知识库查找功能，所以数量为0
     #            （目前stable-diffusion的auto脚本需要使用其中功能，同时需开启stable-diffusion的api功能）

     count: 5
     #最大抽取数量（所有知识库总和）

     step: 2
     #知识库默认上下文步长
librarys: 
  bing: 
    count: 5
     #最大抽取数量
  bingsite: 
     count: 5
     #最大抽取数量
     site: "www.12371.cn"
     #搜索网站
  fess: 
     count: 1
     #最大抽取数量
     fess_host: "127.0.0.1:8080"
     #fess搜索引擎的部署地址
  remote: 
    host: "http://127.0.0.1:17860/api/find"
     #远程知识库地址地址
  rtst: 
     count: 3
     #最大抽取数量
   #   backend: Annoy
     size: 20
     #分块大小"
     overlap: 0
     #分块重叠长度
     model_path: "model/m3e-base"
     #向量模型存储路径
     device: cuda
     #embedding运行设备
  qdrant: 
     path: txt
     #知识库文本路径
     model_path: "model/text2vec-large-chinese"
     #向量模型存储路径
     qdrant_host: "http://localhost:6333"
     #qdrant服务地址"
     device: cpu
     #qdrant运行设备
     collection: qa_collection
     #qdrant集合名称
  kg: 
     count: 5
     #最大抽取数量
     knowledge_path: ""
     #知识库的文件夹目录名称，若留空则为txt
     graph_host: ""
     #图数据库部署地址
     model_path: ""
     #信息抽取模型所在路径"
llm_type: glm6b #rwkv #BOBKING修改LLM类型
#llm模型类型:glm6b、rwkv、llama、replitcode等，详见相关文件
llm_models: 
  rwkv: 
     path: "model/RWKV-4-World-7B-v1-OnlyForTest_52%_trained-20230606-ctx4096-i8.pth"      #rwkv模型位置"
     strategy: "cuda fp16i8"
   #   path: "model/rwkv_ggml_q8.bin"           #rwkv模型位置"
   #   strategy: "Q8_0"       #rwkvcpp:运行方式，设置strategy诸如"Q8_0->16"即可开启，代表运行Q8_0模型在16个cpu核心上
   #记得去https://github.com/saharNooby/rwkv.cpp/releases下最新版本文件替换librwkv.so或rwkv.dll
     #rwkv模型参数"
    
     historymode: state
     #rwkv历史记录实现方式：state、string。注意，对于torch实现，本参数已弃用，因为已经实现自动切换。
     state_source_device: cpu
     #torch实现下，会保存每个会话的state。每个占用2M显存，本参数控制将其复制到内存以节约显存。
     #置为cuda:0，代表state来自cuda:0，且需要将其复制到内存以节约显存。
     #置为cuda:1，同理。
     #置为cpu，代表不需要复制，如果使用cpu计算，或多卡计算需这么设置。
  glm6b: 
     #path: "model/chatglm-6b-int4"
     path: "/chatGLM/chatglm-6b-int4" #BOBKING修改地址
     #glm模型位置"
     strategy: "cuda fp16"
     #cuda fp16	 所有glm模型 要直接跑在gpu上都可以使用这个参数
     #cuda fp16i8	 fp16原生模型 要自行量化为int8跑在gpu上可以使用这个参数
     #cuda fp16i4	 fp16原生模型 要自行量化为int4跑在gpu上可以使用这个参数
     #cuda:0 fp16 *14 -> cuda:1	fp16 多卡流水线并行，使用方法参考RWKV的strategy介绍。总层数28
   #   lora: "model/lora-450"
     #glm-lora模型位置
  baichuan: 
     path: "model/baichuan-7B"
     #模型位置"
     strategy: "cuda fp16"
  aquila: #https://huggingface.co/qhduan/aquilachat-7b
     path: "model/aquilachat-7b"
     #模型位置"
     strategy: "cuda fp16"
  llama: 
     path: "model/stable-vicuna-13B.ggml.q4_2.bin"
     #llama模型位置
   #   strategy: "Q8_0"       #cpp:运行方式，设置strategy诸如"Q8_0"即可开启
     strategy: "cuda fp16i8"
  moss: 
     path: "model/moss-moon-003-sft-plugin-int4"
     #模型位置
     strategy: ""
     #模型参数 暂时不用"
  openai: 
   #   api_host: "https://gpt.lucent.blog/v1" #网友的反代
   #   api_host: "https://api.openai.com/v1" #官方地址
     api_host: "http://127.0.0.1:8000/v1" #rwkv runner
     
  replitcode: 
     path: "model/replit-code-v1-3b"
     #replitcode模型位置
     #说明：目前模型参数和chat模型差异较大，写死了，不能通过wenda界面配置，需要调整自行到llm_replitcode.py 文件中调整，或放开wenda界面参数
     #y = model.generate(x, max_length=100, do_sample=true, top_p=0.95, top_k=4, temperature=0.2, num_return_sequences=1, eos_token_id=tokenizer.eos_token_id)
     #模型地址：https://huggingface.co/replit/replit-code-v1-3b ，约10g
     #作用代码补全：问：def fibonacci(n):
     #答：def fibonacci(n):
     #if n == 0:
     #return 0
     #elif n == 1:
     #return 1
     #else:
     #return fibonacci(n-1) + fibonacci(n-2)
     #print(fibonacci(10))
     strategy: "cuda fp16"
    #因我的3070只有8g内存，所以是先把模理加载到内存进行精度转换，至少要32g系统内存， fp16 占用不到6g显存,fp32 超过8g未测试"

**Comment by shadowbox-cash** [comment]
> 把问题描述清楚，不要弄上来一大堆

简单的描述，就是运行 python3 plugins/gen_data_st.py 报错“加载配置失败，改为加载默认配置”，

**Comment by l15y** [comment]
没事
可以用默认配置文件复制出了修改，去读文档
