### ISSUE TITLE
模型加载完成，没有看到WebUI的URL

### ISSUE THREAD

**Issue by shadowbox-cash** [wenda-LLM/wenda#388]
执行wenda.py ，似乎没有报错，但是没有webui的URL，我看其他教程都有serving on ....广域网IP加端口，这是为什么？

以下是执行信息，请帮助！

(myenv) root@48376ad10eec:~/wenda# python wenda.py 
Namespace(Config='config.yml', Port=None, Logging=None, LLM_Type=None)
library:
  count: 5
  step: 2
  strategy: calc:2 rtst:2 agents:0
librarys:
  bing:
    count: 5
  bingsite:
    count: 5
    site: www.12371.cn
  fess:
    count: 1
    fess_host: 127.0.0.1:8080
  kg:
    count: 5
    graph_host: ''
    knowledge_path: ''
    model_path: ''
  qdrant:
    collection: qa_collection
    device: cpu
    model_path: model/text2vec-large-chinese
    path: txt
    qdrant_host: http://localhost:6333
  remote:
    host: http://127.0.0.1:17860/api/find
  rtst:
    count: 3
    device: cuda
    model_path: model/m3e-base
    overlap: 0
    size: 20
llm:
  path: /chatGLM/chatglm-6b-int4
  strategy: cuda fp16
llm_type: glm6b
logging: false
port: 17860

[['cuda', 'fp16']]
No sentence-transformers model found with name model/m3e-base. Creating a new one with MEAN pooling.
知识库加载完成
No compiled kernel found.
Compiling kernels : /root/.cache/huggingface/modules/transformers_modules/local/quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 /root/.cache/huggingface/modules/transformers_modules/local/quantization_kernels_parallel.c -shared -o /root/.cache/huggingface/modules/transformers_modules/local/quantization_kernels_parallel.so
Load kernel : /root/.cache/huggingface/modules/transformers_modules/local/quantization_kernels_parallel.so
Setting CPU quantization kernel threads to 20
Using quantization cache
Applying quantization to glm layers
模型加载完成

**Comment by l15y** [comment]
port: 17860已经显示
IP地址是你服务器IP
