### ISSUE TITLE
有几个报错，请教一下，问题如下：

### ISSUE THREAD

**Issue by dream-desktop** [wenda-LLM/wenda#390]
请教一下。
以前用的是都是正常，今天安装6.16号的版本以后有了很多报错：
1.  RWKV（cpp）
     新下载的rwkv.dll要放在哪呢
2.  aquila
     总是cuda爆内存，能不能用纯cpu？
3.  baichuan
     同样，能不能用纯cpu？
4.  RWKV（cuda)
     这是什么错误？
![image](https://github.com/wenda-LLM/wenda/assets/97580976/9da2110d-d370-43fe-9dc3-4676560e224a)
5.  LLAMA 
    跟上面一样错误
![image](https://github.com/wenda-LLM/wenda/assets/97580976/3db04dd7-563e-42ae-a0bd-2759ad7df734)

**Comment by l15y** [comment]
1搜一下
4yml语法错误
