### ISSUE TITLE
百度网盘不能下载

### ISSUE THREAD

**Issue by freedomme** [wenda-LLM/wenda#392]
放到百度网盘内容不能下载，提示侵权

**To Reproduce**
放到百度网盘内容不能下载，提示侵权

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ysyx2008** [comment]
正想说这个，公告里的百度网盘链接已经失效了。

**Comment by AbelKeithsun** [comment]
对呀，失效了怎么办？

**Comment by AbelKeithsun** [comment]
有没有同学做p2p下载的？

**Comment by l15y** [comment]
如果有适合国内网络的P2P方案，我愿意一试
