### ISSUE TITLE
虚拟环境下自行安装还需要安装 cchardet，如果再有不明错误则还需要cython

### ISSUE THREAD

**Issue by ilovesouthpark** [wenda-LLM/wenda#400]
自行安装指南可以再详细一点：）

**Comment by fangg2000** [comment]
VM虚拟环境吗？还是annconda的？如果是前者建议你不用试了（可以改双系统），VM虚拟环境不支持显卡驱动安装，你就用不了CUDA，如果用CPU……这个好像没什么好搞的。
