### ISSUE TITLE
请问如何使用office调用知识库,目前的版本api/chat只能聊天

### ISSUE THREAD

**Issue by xs818818** [wenda-LLM/wenda#403]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by l15y** [comment]
为什么不行？描述清楚

**Comment by xs818818** [comment]
我使用的方法是：

**Comment by xs818818** [comment]
Sub chatbao()
 Dim selectedText As String
 Dim apiKey As String
 Dim respose As Object, re As String
 Dim midString As String
 Dim ans As String
 If Selection.Type = wdSelectionNormal Then
     selectedText = Selection.Text
     selectedText = Replace(selectedText, ChrW$(13), "")
     URL = "http://45.253.65.23:15083/api/chat"
     Set response = CreateObject("MSXML2.XMLHTTP")
     response.Open "POST", URL, False
     response.setRequestHeader "Content-Type", "application/json"
     response.Send "{""prompt"":""" & selectedText & """,""temperature"":1.3,""top_p"":0.5,""max_length"":2048,""history"":[],""zhishiku"": True,}"
     ans = response.responseText
     Selection.Text = selectedText & vbNewLine & ans
 Else
   Exit Sub
 End If
End Sub

**Comment by xs818818** [comment]
Sub chatbao()
 Dim selectedText As String
 Dim apiKey As String
 Dim respose As Object, re As String
 Dim midString As String
 Dim ans As String
 If Selection.Type = wdSelectionNormal Then
     selectedText = Selection.Text
     selectedText = Replace(selectedText, ChrW$(13), "")
     URL = "http://127.0.0.1:17086/api/chat"
     Set response = CreateObject("MSXML2.XMLHTTP")
     response.Open "POST", URL, False
     response.setRequestHeader "Content-Type", "application/json"
     response.Send "{""prompt"":""" & selectedText & """,""temperature"":1.3,""top_p"":0.5,""max_length"":2048,""history"":[],""zhishiku"": True,}"
     ans = response.responseText
     Selection.Text = selectedText & vbNewLine & ans
 Else
   Exit Sub
 End If
End Sub

**Comment by xs818818** [comment]
但是得到的结果还是单纯的chatglm的返回结果，我希望是调用知识库后组织的语言

**Comment by l15y** [comment]
去看我给的程序

**Comment by sccsbc** [comment]
你给的程序在哪里看啊

**Comment by l15y** [comment]
> 你给的程序在哪里看啊

https://github.com/wenda-LLM/WDOC
文档比较简单，有时间可以帮我完善下
