### ISSUE TITLE
无法安装fess

### ISSUE THREAD

**Issue by Lufffya** [wenda-LLM/wenda#414]
![image](https://github.com/wenda-LLM/wenda/assets/49063302/933b3cd0-f047-4f0a-a1fb-a48abd8a09cc)

按照此步骤，无法安装成功

**Comment by Lufffya** [comment]
具体就是 
![image](https://github.com/wenda-LLM/wenda/assets/49063302/2163bb9d-72e3-4ddb-8ad8-8889b42abc65)

**Comment by yjy8749** [comment]
你饿java环境没有配置好，配置一下java环境

**Comment by pengber** [comment]
java解压后链接有问题吧, 要把对应的目录换成自己的安装目录

**Comment by lowpair** [comment]
> win11安装fess最新版本，使用fess的json接口无效，fess返回 Page Not Found Check the url. /json/ 哪位朋友遇到过吗？

http://127.0.0.1:8080/api/v1/documents?q=keywords

**Comment by YuLing91** [comment]
请问有人在苹果电脑安装成功的吗？
