### ISSUE TITLE
chatglm2-6b-int4模型报显存不足

### ISSUE THREAD

**Issue by fluxlinkage** [wenda-LLM/wenda#418]
**Describe the bug**
8G显存，可以运行chatglm2-6b-int4模型，但是使用闻达启动器“运行服务ChatGLM6B”会报显存不足的错误。

**To Reproduce**
8G显存的显卡，Win10系统。下载chatglm2-6b-int4模型，放置在model目录下，闻达启动器使用默认配置，“程序运行”>“运行服务ChatGLM6B”，命令行会报错。
torch.cuda.OutOfMemoryError: CUDA out of memory...

**Expected behavior**
应该可以正常运行的。

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**Additional context**
经过尝试发现一个临时的解决方案：
修改llms/llm_glm6b.py第70-71行。
把
    model = AutoModel.from_pretrained(
        settings.llm.path, local_files_only=True, trust_remote_code=True, device=device, revision="v1.1.0")
改成
    model = AutoModel.from_pretrained(
        settings.llm.path, local_files_only=True, trust_remote_code=True, revision="v1.1.0")
即删掉“, device=device”
就可以正常启动了！
原理不详……

**Comment by zhuang-maowei** [comment]
删掉device参数，默认是cpu和内存

**Comment by l15y** [comment]
可以将rtst在CPU运行，节约显存
