### ISSUE TITLE
更新后生成知识库索引失败

### ISSUE THREAD

**Issue by zhuyunqi1990** [wenda-LLM/wenda#423]
**Describe the bug**
隔了很久更新了一下新版（全部删掉重新下载了一遍），正常加载模型和知识库且可以进入系统开始对话，但是没了索引就想重新生成知识库

**To Reproduce**
想跟之前一样，手动在自己的虚拟环境下运行plugins下的gen_data_st.py文件

**Expected behavior**
显示找不到plugins库
Traceback (most recent call last):
  File "E:\wenda-main\plugins\gen_data_st.py", line 15, in <module>
    from plugins.common import success_print, error_print
ModuleNotFoundError: No module named 'plugins'
奇怪的是运行wenda.py文件没有这个问题
**Screenshots**
![image](https://github.com/wenda-LLM/wenda/assets/132052151/75731732-d925-4650-a306-e78b445ddc35)

**Comment by ImmNaruto** [comment]
你在wenda-main目录下执行这句命令python plugins/gen_data_st.py就行，它是按相对路径来的所以提示你找不到plugins

**Comment by zhuyunqi1990** [comment]
> 你在wenda-main目录下执行这句命令python plugins/gen_data_st.py就行，它是按相对路径来的所以提示你找不到plugins

多谢多谢，实在很久没更新了
