### ISSUE TITLE
chatglm-130b  api 更新

### ISSUE THREAD

**Issue by linuxdevopscn** [wenda-LLM/wenda#425]
chatglm-130b  api的sdk更新了，鉴权也更新了现在只有Api key了，没有Public key了，新的用户只能看到api key希望大佬们更新一下。

**Comment by diannaojiang** [comment]
现在开放的是chatglm-std和lite 并不是之前的130b   所以这个应该是新增而不是更新

**Comment by linuxdevopscn** [comment]
> 现在开放的是chatglm-std和lite 并不是之前的130b 所以这个应该是新增而不是更新

看文档之前的鉴权方式九月份就停用了，之前的不太了解现在是std和lite
