### ISSUE TITLE
No sentence-transformers model found with name model/m3e-base. Creating a new one with MEAN pooling.

### ISSUE THREAD

**Issue by shenmadouyaowen** [wenda-LLM/wenda#434]
除了报:No sentence-transformers model found with name model/m3e-base. Creating a new one with MEAN pooling. 其他都正常,怎么样才能让model/m3e-base加载成功?
![image](https://github.com/wenda-LLM/wenda/assets/12426724/cf649a4a-1435-4bbc-ba42-7ee88f658f1c)
![image](https://github.com/wenda-LLM/wenda/assets/12426724/a419ef98-217c-4646-8d59-4fc86ad270ed)

**Comment by lwo2002** [comment]
这不是错误，不影响使用。

**Comment by shenmadouyaowen** [comment]
好的,谢谢,顺便问一下可以支持数据库么
