### ISSUE TITLE
我用文档中的原问题，AI还是说未找到

### ISSUE THREAD

**Issue by heiheiheibj** [wenda-LLM/wenda#445]
![image](https://github.com/wenda-LLM/wenda/assets/6910198/c1e99aa8-7f10-4c6e-8b08-9275d1e80708)
它都已经匹配出来 天师问答.TXT的知识库，但回答要么是乱答，要么就说没到相关信息
我提的问题是 天师问答.TXT 中的原话。
用的是GLM6B2，谢谢

**Comment by l15y** [comment]
换模型

**Comment by heiheiheibj** [comment]
谢谢，模型路径问题。
另外试了下，GLM6B2比rwkv效果好不少。
