### ISSUE TITLE
请问一下WENDA API的接口参数是什么样的

### ISSUE THREAD

**Issue by heiheiheibj** [wenda-LLM/wenda#451]
按什么参数格式向  http://127.0.0.1:17860/api 这个接口POST数据呢
谢谢

**Comment by diannaojiang** [comment]
已经更新了和openai一致的/chat/completions 接口，后续会继续补全此接口的各项参数和接口文档

**Comment by diannaojiang** [comment]
[文档](https://github.com/wenda-LLM/wenda/blob/main/docs/api.md)
