### ISSUE TITLE
用rwkv出现错误错误probability tensor contains either inf, nan or element < 0

### ISSUE THREAD

**Issue by fryng** [wenda-LLM/wenda#461]
![image](https://github.com/wenda-LLM/wenda/assets/25688907/81a5a03e-7734-4cf4-a210-b11237c62d03)
模型加载成功，但是在问答时出现错误
![image](https://github.com/wenda-LLM/wenda/assets/25688907/a2a53177-9e9d-4594-a1e8-f16a6ec40884)

**Comment by l15y** [comment]
你用的模型不能量化
