### ISSUE TITLE
尝试加载chatglm2-6b-32k模型报错

### ISSUE THREAD

**Issue by gxandys** [wenda-LLM/wenda#468]
32k的模型从huggingface上下的，在config.yml里改好了路径。strategy参数无论是“cuda fp16"还是改成"cuda fp32"都会报如下错误：
![QQ截图20230807105648](https://github.com/wenda-LLM/wenda/assets/52304029/b3238ff7-2c22-4275-89c4-5e72fb50ef97)
应该是刚尝试加载就出错了，显存占用也压根都没变化，还是没运行时的数。求问该怎么办呢？

**Comment by sidatian1** [comment]
遇到同样问题，求官方解答

**Comment by l15y** [comment]
模型没下好
