### ISSUE TITLE
知识库回答时语音重复播放答案

### ISSUE THREAD

**Issue by 4135541355** [wenda-LLM/wenda#469]
知识库回答时语音重复播放答案

重现该行为的步骤：
1. 百度懒人包716版本，启动器启动知识库生成并运行服务glm6b
2. 在网页版中单击知识库和文本阅读
3. 输入（甘肃武威雷台东汉墓清理简报）
4. 同一个答案重复语音播放两遍,py窗口答案也是报出两遍。

个人理解是文本阅读功能取的是py窗口的值而不是网页端文本的值

**截图**

<img width="1075" alt="微信图片_20230807130001" src="https://github.com/wenda-LLM/wenda/assets/68000035/21055559-6908-4dab-a4a6-2fa414187314">

<img width="744" alt="微信图片_20230807125943" src="https://github.com/wenda-LLM/wenda/assets/68000035/5dd041ae-7923-464e-849c-eba8055d9155">

**桌面（请填写以下信息）：**
  - 操作系统：win10
  - 浏览器：chrome

**Comment by l15y** [comment]
语音本来就需要二次开发，你的需求可以用快速知识库
