### ISSUE TITLE
wenda是否是以检索为主要功能，对于学习创作文章之类的能力仍有欠缺？

### ISSUE THREAD

**Issue by AceYang666** [wenda-LLM/wenda#478]
本人在部署完成后，在知识库中增加了多篇公文，以期wenda通过训练能够以他们为模板写一篇较为规范的公文。
然而在加载完知识库后启用知识库模式后进行询问“请写一篇以改革为主题的通知”，wenda显示“未匹配到知识库，本回答由模型提供”；在询问“关于改革的通知”后会检索到相应的知识库内容，但其会对内容进行总结而不是给出类似的范例，如图
![image](https://github.com/wenda-LLM/wenda/assets/58732378/616486a5-ab5d-4852-8e4c-19ee05ee3935)

**Comment by l15y** [comment]
不是这么用的。用论文功能
