### ISSUE TITLE
构建知识库索引后搜索不到内容

### ISSUE THREAD

**Issue by Sowhat007** [wenda-LLM/wenda#479]
最近下载了最新版wenda，更新了依赖包，发现在聊天中无法匹配到知识库，执行了以下操作：
1，按教程先将文档放入txt文件夹，执行python plugins/gen_data_st.py显示完成无报错，在memorey文件夹中有default文件夹并存在索引文件（一个.fess文件一个.kpl文件）；
2，执行wenda.py显示知识库加载成功无报错，按文档内容的关键词询问显示“未匹配到知识库”。
3，老版本的wenda可以正常按文档内容查询。
4，查看了config文件，没有发现明显问题。
5，查询知识库可以搜到东西，但是同样的关键词在聊天界面中进行知识库搜索无法匹配到内容。
6，向量知识库管理工具中也可以查询到关键词。
请问这问题如何修复？提前感谢！

**Comment by Sowhat007** [comment]
不断重新构建索引，测试之后，突然可以了。神奇！

**Comment by Torala** [comment]
我也是一样的问题，当时重复构建索引也没有解决这个问题。
txt文件夹里面只放了一个txt，在测试搜索中显示“No data available”，很奇怪。
