### ISSUE TITLE
'HuggingFaceEmbeddings' object is not callable

### ISSUE THREAD

**Issue by LapisRanger** [wenda-LLM/wenda#503]
运行buils_rtst_default_index.bat脚本可以知识库能够正常加载txt文件夹下的文件建立索引，但是查询不到任何知识库，点击查询后就会提示‘'HuggingFaceEmbeddings' object is not callable’，但也不会退出，能继续使用模型和网页端。

**Comment by Erkang1992** [comment]
我和你一样的情况但是我报的'NoneType' object has no attribute 'embedding_function'

**Comment by AlvinAi96** [comment]
我也遇到相同问题，而且知识库问答下，回复根本不是知识库内的内容

**Comment by Eins0** [comment]
这个问题我没有找到官方解答，因此debug了很久，最终解决
应该是Langchain版本问题，
plugins/zhishiku_rtst.py 第62行
` embedding = get_vectorstore(memory_name).embedding_function(s)`
0.0329版本的langchain HuggingFaceEmbeddings类没有这个api，需要改成
` embedding = get_vectorstore(memory_name).embedding_function.embed_query(s)`
@l15y 作者有空可以确认下

**Comment by AlvinAi96** [comment]
> 这个问题我没有找到官方解答，因此debug了很久，最终解决 应该是Langchain版本问题， plugins/zhishiku_rtst.py 第62行 ` embedding = get_vectorstore(memory_name).embedding_function(s)` 0.0329版本的langchain HuggingFaceEmbeddings类没有这个api，需要改成 ` embedding = get_vectorstore(memory_name).embedding_function.embed_query(s)` @l15y 作者有空可以确认下

谢谢，改完就没问题了！

**Comment by LapisRanger** [comment]
> 这个问题我没有找到官方解答，因此debug了很久，最终解决 应该是Langchain版本问题， plugins/zhishiku_rtst.py 第62行 ` embedding = get_vectorstore(memory_name).embedding_function(s)` 0.0329版本的langchain HuggingFaceEmbeddings类没有这个api，需要改成 ` embedding = get_vectorstore(memory_name).embedding_function.embed_query(s)` @l15y 作者有空可以确认下

我的改完后也可以调用知识库了，感谢大佬！

**Comment by Chen-mingxuan** [comment]
大佬太强了 我一直没找到问题 终于解决了

**Comment by wyjjs31** [comment]
> 这个问题我没有找到官方解答，因此debug了很久，最终解决 应该是Langchain版本问题， plugins/zhishiku_rtst.py 第62行 ` embedding = get_vectorstore(memory_name).embedding_function(s)` 0.0329版本的langchain HuggingFaceEmbeddings类没有这个api，需要改成 ` embedding = get_vectorstore(memory_name).embedding_function.embed_query(s)` @l15y 作者有空可以确认下

谢谢！ 解决问题了

**Comment by sspeedtail** [comment]
> 我和你一样的情况但是我报的'NoneType' object has no attribute 'embedding_function'

请问你解决了吗？我也是这个问题
